name: food_portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http:
  flutter_animate: ^4.5.0
  visibility_detector: ^0.3.3
  url_launcher: ^6.0.20
  # firebase_core:
  # cloud_firestore:
  # firebase_auth:
  # google_maps_flutter: ^2.6.1
  cupertino_icons: ^1.0.6
  responsive_builder:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Gaby
      fonts:
        - asset: assets/fonts/Gaby.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel.ttf
    - family: Sweet-Peas
      fonts:
        - asset: assets/fonts/Sweet-Peas.ttf
    - family: Hunters
      fonts:
        - asset: assets/fonts/Hunters.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
